services:
  - name: web
    type: web
    buildCommand: pip install -r requirements.txt
    # startCommand: gunicorn backend.wsgi:application
    startCommand: |
      python manage.py migrate
      gunicorn backend.wsgi:application


    runtime:
  pythonVersion: 3.9