# Generated by Django 4.2.6 on 2023-11-21 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SavedRecipes', '0002_savedrecipe_delete_shoppinglistitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedrecipe',
            old_name='recipe_url',
            new_name='url',
        ),
    ]
