# Generated by Django 4.2.6 on 2023-11-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teathyme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
